### ISSUE TITLE
submitting a set of machines

### ISSUE THREAD

**Issue by mrfreezer** [nikp123/wake-on-arp#8] opened 2021-07-27 14:28 UTC
i have more than one machine i would like to wake on arp. instead of starting several WoA-instances wouldn't it be nice if one could supply a list of ips and the corresponding mac adresses?

ingo

**Comment by Falcosc** [comment] 2021-07-27 15:13
We should not forget to extend the logging output to tell which target was requested.

I love this request just because it is simple but unnecessarily painful to implement and memory manage a list with unknown length in C.
Sounds like a 30min job (https://github.com/nikp123/wake-on-arp/issues/1#issuecomment-882834739) 😄

**Comment by mrfreezer** [comment] 2021-07-27 15:53
¯\\\_(ツ)\_/¯

**Comment by nikp123** [comment] 2021-07-27 18:04
im going to be lazy and make a memory filling version, you can complain later.

**Comment by nikp123** [comment] 2021-07-27 18:05
though to be frank, even with this version youll be able to run like 100 + devices on your dreamcast's RAM, so you should be good.

**Comment by nikp123** [comment] 2021-07-27 18:09
> Sounds like a 30min job 

n̸͔̏̌ͮͅo̘̪̱̲̙͂̀

**Comment by nikp123** [comment] 2021-07-27 18:20
> I love this request just because it is simple but unnecessarily painful to implement and memory manage a list with unknown length in C.

also regarding that one of my colleagues suggests i switch to rust or zig for my own sanity

**Comment by nikp123** [comment] 2021-07-27 20:38
try, see if it works

**Comment by nikp123** [comment] 2021-07-27 20:38
two hours... i should speedrun C

**Comment by mrfreezer** [comment] 2021-07-27 21:15
to me this looks like it works like a charme... thanks a lot.

**Comment by Falcosc** [comment] 2021-07-27 21:33
Who needs high-level languages and all these frameworks? Just constructing a linked list and calling add would be boring.

But I am disappointed at how straightforward this solution is. The introduction of gateway ip and booleans was much more funny. Hope it is ok for you if we have fun to follow your pain ;)

Cool that you are responding so fast. It seems like you are waiting at your issue tracker to solve anything.

I have just started to spread the existence of your tool a bit because I really think this is a game changer and still don't believe that I can't find a dozen others of this kind. 

@mrfreezer Was it a coincidence that you start using this tool a year after its creation, right on the day when I started telling people about it?

**Comment by mrfreezer** [comment] 2021-07-27 22:08
completely random.

to be frank i just started deploying a remote desktop gateway infrastructure through which my coworkers can access their desktops at the office. you know, homeoffice and corona and things. on one hand we have some folks who take turns in working at the office and from home and sometimes they shut down their machines in the evening - some accidently out of routine, some on purpose thinking they would be at the office at the next day but then staying at home for some reason.
the other thing is that many of us are pretty environment-aware and we would LOVE to be able to shut down our machines to save energy.
i already had this idea but dismissed it for now since i didn't think there would be much demand for it but as soon as some colleagues asked for it themselves i went to town on this topic.

i'm also trying to replace the microsoft servers with the linux remote desktop gateway by bolke de bruin https://github.com/bolkedebruin/rdpgw - in an ideal world the gateway should wake up the hosts itself. but maybe one day...

anyways, this was already a large step forward and the last issues i will fix on my side.

ingo

**Comment by nikp123** [comment] 2021-07-28 05:15
@mrfreezer Glad I could somehow help, I mean, keeping devices awake for the sake of remoting in is indeed wasteful. I love these simple, but elegant solutions to these sorts of issues.

**Comment by Falcosc** [comment] 2021-07-28 06:03
10 Years ago, I did solve this problem with a Java-based HTTP redirect service which did send the magic package and waited for a ping response before sending the redirect to the client.

It is just unreal that it took so long to get a nice tool for that problem. Back then it was even worse because everything had an idle power consumption of 20-30W.

**Comment by nikp123** [comment] 2021-07-28 06:30
> because everything had an idle power consumption of 20-30W.

to be honest, that was the cpu alone probably, the whole system was about in the 50-80 range (excluding the monitor)

**Comment by Falcosc** [comment] 2021-07-28 06:49
My Sandybridge Server was able to hit 20-30W, it already had an iGPU, but true normal systems from this time was much worse.

**Comment by nikp123** [comment] 2021-07-29 17:16
since the issue is solved, Im closing this issue

**Closed as completed by nikp123** 2021-07-29 17:16 UTC
